version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username  
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password  
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url   

phases:
  install:
    runtime-versions:
      python: 3.11  # Specify the Python version you need
    commands:
      - echo "Installing dependencies..."
      - pip install -r Project-DockerHub/requirements.txt  # Install Python dependencies

  pre_build:
    commands:
      - echo "Running tests..."
      # Add any test or setup commands here if needed

  build:
    commands:
      - echo "Building Docker image..."
      - cd Project-DockerHub/  # Navigate to the app directory (if necessary)
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/renu-python-app:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/renu-python-app:latest"

  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'  # Adjust as needed to capture relevant files
  base-directory: ../Project-DockerHub  # The base directory to include artifacts from
